source "http://rubygems.org"

gem "sinatra"
gem "sinatra-contrib"
gem "nokogiri"
gem "json"
gem "activerecord"
gem "sinatra-activerecord"
gem "rmagick", "~> 2.13.1"
gem "public_suffix"
gem "thin"
gem "async_sinatra"
